name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Build
      run: |
        cd src
        g++ main.cpp file_transfer.cpp -o file_transfer
