name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up MSYS2 environment
      uses: mattn/gom@v0.3
      with:
        msys2: x86_64
    - name: Build
      run: |
        cd src
        g++ main.cpp file_transfer.cpp -o file_transfer
